### ISSUE TITLE
Subserv crashes when deleting an address

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/subserv#2]
When I replace the addressing config with an empty json object, the subserv pod crashes:

pod removed for mytopic: {"name":"topic-mytopic-1-r4sdy","ip":"172.17.0.11","status":"Running","ready":true,"ports":{"broker":{"amqp":5673,"core":61616},"router":{"amqp":5672},"forwarder":{"health":8080}}}
/usr/local/subserv/qdr.js:131
    this.connection.close();
                   ^
TypeError: Cannot read property 'close' of undefined
    at Router.close (/usr/local/subserv/qdr.js:131:20)
    at Pod.close (/usr/local/subserv/podgroup.js:44:17)
    at PodGroup.removed (/usr/local/subserv/podgroup.js:57:25)
    at null.<anonymous> (/usr/local/subserv/topic.js:48:21)
    at emit (events.js:107:17)
    at null.<anonymous> (/usr/local/subserv/podwatch.js:97:15)
    at IncomingMessage.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at IncomingMessage.Readable.push (_stream_readable.js:126:10)
    at HTTPParser.parserOnBody (_http_common.js:132:22)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by grs** [comment]
How do I reproduce this? I tried oc replace on the maas config map with an empty map, but nothing seemed to happen, existing queue and topic remained and were not deleted.

**Comment by lulf** [comment]
I've not been able to reproduce this. I've seen it crash multiple times, but most of the times, I end up reproducing https://github.com/EnMasseProject/subserv/issues/1 .
